language:
        - python 
        - r
python:
        - 3.5
r:
        - 3.3

before_script:
        # opencv dependency script
        git clone https://github.com/jayrambhia/Install-OpenCV
        cd Ubuntu
        chmod +x * 
        ./opencv_latest.sh

install:
        # install pfla package
        pip3 install pfla

script: pfla/test.py


