os: linux
dist: trusty
language: python
before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
  - conda env create -f environment.yml
  - conda activate pfla
  - mkdir shapes
  - cd shapes
  - conda skeleton cran --recursive shapes
  - conda build r-shapes
  - conda install --yes -c /home/travis/miniconda3/envs/pfla/conda-bld r-shapes
  - pip3 install .
script:
  - pytest -vslr pfla --cov=pfla --cov-report=term-missing
