os: linux

dist: xenial

group: stable

language: python 

python:
        - 3.5

before_install:
        # install R
        - sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list
        - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
        - gpg -a --export E084DAB9 | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get install r-base r-base-dev

install: pip3 install pfla

before_script:
        - cp pfla/data/shape_predictor_68_face_landmarks.dat /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/pfla/data/
        - pwd 

script: python3 pfla/test.py


