os: linux
dist: xenial
group: stable
language: python
python:
    - 3.5
cache: pip

before_install:
    # install R
    - sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list
    - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
    - gpg -a --export E084DAB9 | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install r-base r-base-dev
    - pip3 install -r requirements.txt

install: pip3 install .
script:
    - pytest -vslr pfla --cov=pfla --cov-report=term-missing
