name: pfla
channels:
  - conda-forge
dependencies:
  - conda-build
  - numpy
  - pandas
  - dlib
  - progress
  - rpy2
  - opencv
  - pytest
  - pytest-cov
  - requests
  - r-base
  - r-foreach
  - pip:
    - imutils
